In [24]:
import pandas as pd
import os
import numpy as np
from scipy import signal
import cv2

In [25]:
def smooth(pix_num):
    win_gauss = signal.gaussian(10,3)
    smooth_pix_num = signal.convolve(pix_num, win_gauss, mode='same', method = 'direct') / win_gauss.sum()
    return(smooth_pix_num)
def edge_detect(smooth_pix_num):
    pix_value = np.asarray(smooth_pix_num)
    pix_thresh = 500
    motion = (pix_value > pix_thresh)
    frames = np.array(range(len(motion)-1))
    In_frame = frames[motion[1:] & ~motion[:-1]]+1
    Out_frame = frames[~motion[1:] & motion[:-1]]+1
    return(In_frame, Out_frame)

In [29]:
path = r'C:\Users\Daniellab\Desktop\Light_level_videos_second_batch\Data\Step1_Tanvi_Method'
output_path = r'C:\Users\Daniellab\Desktop\Light_level_videos_second_batch\Data\Step2_Tanvi_Method'
data = [(os.path.join(root, name), name[0:-4])
               for root, dirs, files in os.walk(path)
               for name in files
               if name.endswith('.csv')]
data

[('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m12.csv',
  'L0.1_c-3_m12'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m2.csv',
  'L0.1_c-3_m2'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m20.csv',
  'L0.1_c-3_m20'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m21.csv',
  'L0.1_c-3_m21'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m22.csv',
  'L0.1_c-3_m22'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m23.csv',
  'L0.1_c-3_m23'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_Method\\L0.1_c-3_m24.csv',
  'L0.1_c-3_m24'),
 ('C:\\Users\\Daniellab\\Desktop\\Light_level_videos_second_batch\\Data\\Step1_Tanvi_

In [32]:
for video in data:
    df = pd.read_csv(video[0])
    filename = video[1]
    
    print('working on ' + filename)
    with open(os.path.join(output_path, 'Step2_SummaryFile.txt'), 'a') as log_text:
        log_text.write('\n' + 'working on ' + filename + '\n')
    
    pix_per_frame = df.NumPixel.values
    smooth_pix_num = smooth(pix_per_frame)
    In, Out = edge_detect(smooth_pix_num)
    
    if In.size > Out.size:
        In = In[:Out.size]
    elif In.size < Out.size:
        Out = Out[1:]
    
    frames_in_view = Out - In
     
    nd = {'In_Frame': In, 'Out_Frame': Out, 'Frames_In_View': frames_in_view}
    new_df = pd.DataFrame(data=nd)
    new_df.to_csv(output_path + '/' + filename + '_MothInOut.csv')
    
    if frames_in_view.size == 0:
        print('no moth movement detected ' + filename)
        with open(os.path.join(output_path, 'Step2_SummaryFile.txt'), 'a') as log_text:
            log_text.write('\n' + 'no moth movement detected ' + filename + '\n')
    else:
        print('done with ' + filename)
        with open(os.path.join(output_path, 'Step2_SummaryFile.txt'), 'a') as log_text:
            log_text.write('done with ' + filename + '\n')

working on L0.1_c-3_m12
done with L0.1_c-3_m12
working on L0.1_c-3_m2
done with L0.1_c-3_m2
working on L0.1_c-3_m20
done with L0.1_c-3_m20
working on L0.1_c-3_m21
done with L0.1_c-3_m21
working on L0.1_c-3_m22
done with L0.1_c-3_m22
working on L0.1_c-3_m23
done with L0.1_c-3_m23
working on L0.1_c-3_m24
done with L0.1_c-3_m24
working on L0.1_c-3_m25
done with L0.1_c-3_m25
working on L0.1_c-3_m32
done with L0.1_c-3_m32
working on L0.1_c-3_m34
done with L0.1_c-3_m34
working on L0.1_c-3_m37
done with L0.1_c-3_m37
working on L0.1_c-3_m38
done with L0.1_c-3_m38
working on L0.1_c-3_m39
done with L0.1_c-3_m39
working on L0.1_c-3_m40
done with L0.1_c-3_m40
working on L0.1_c-3_m41
done with L0.1_c-3_m41
working on L0.1_c-3_m43
done with L0.1_c-3_m43
working on L0.1_c-3_m44
done with L0.1_c-3_m44
working on L0.1_c-3_m5
done with L0.1_c-3_m5
working on L0.1_c-3_m8
done with L0.1_c-3_m8
working on L50_c-3_m10
done with L50_c-3_m10
working on L50_c-3_m12
done with L50_c-3_m12
working on L50_c-3_m13


In [23]:
path_10 = r'C:\Users\Daniellab\Desktop\Light_level_videos_c-10\Data\Step1'
output_path_10 = r'C:\Users\Daniellab\Desktop\Light_level_videos_c-10\Data\Step2'
data_10 = [(os.path.join(root, name), name[0:-4])
               for root, dirs, files in os.walk(path_10)
               for name in files
               if name.endswith('.csv')]

In [24]:
for video in data_10:
    df = pd.read_csv(video[0])
    filename = video[1]
    
    print('working on ' + filename)
    with open(os.path.join(output_path_10, 'Step2_SummaryFile.txt'), 'a') as log_text:
        log_text.write('\n' + 'working on ' + filename + '\n')
    
    pix_per_frame = df.NumPixel.values
    smooth_pix_num = smooth(pix_per_frame)
    In, Out = edge_detect(smooth_pix_num)
    
    if In.size > Out.size:
        In = In[:Out.size]
    elif In.size < Out.size:
        Out = Out[1:]
    
    frames_in_view = Out - In
     
    nd = {'In_Frame': In, 'Out_Frame': Out, 'Frames_In_View': frames_in_view}
    new_df = pd.DataFrame(data=nd)
    new_df.to_csv(output_path_10 + "\\" + filename + '_MothInOut.csv')
    
    if frames_in_view.size == 0:
        print('no moth movement detected ' + filename)
        with open(os.path.join(output_path_10, 'Step2_SummaryFile.txt'), 'a') as log_text:
            log_text.write('\n' + 'no moth movement detected ' + filename + '\n')
    else:
        print('done with ' + filename)
        with open(os.path.join(output_path_10, 'Step2_SummaryFile.txt'), 'a') as log_text:
            log_text.write('done with ' + filename + '\n')

working on L0.1_c-10_m1
done with L0.1_c-10_m1
working on L0.1_c-10_m3
done with L0.1_c-10_m3
working on L0.1_c-10_m5
done with L0.1_c-10_m5
working on L0.1_c-10_m6
done with L0.1_c-10_m6
working on L0.1_c-10_m7
done with L0.1_c-10_m7
working on L50_c-10_m1
done with L50_c-10_m1
working on L50_c-10_m3
done with L50_c-10_m3
working on L50_c-10_m5
done with L50_c-10_m5
working on L50_c-10_m6
done with L50_c-10_m6
working on L50_c-10_m7
done with L50_c-10_m7


In [17]:
bob = np.array([[[0,0]], [[10,0]], [[10,10]], [[5,4]]])
area = cv2.contourArea(bob)
areas = np.asarray(area)
areas[areas < 45] = 0
if np.any(areas):
    print(bob)

[[[ 0  0]]

 [[10  0]]

 [[10 10]]

 [[ 5  4]]]


In [ ]:
_, contours, hierarchy = cv2.findContours(close, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    area = [cv2.contourArea(c) for c in contours]
    areas = np.asarray(area)
    areas[areas < 500] = 0
    
    if (len(contours) >= 1) & np.any(areas):